Pages/index yummy
Ariel0508/FlavorTrail pull request #21
Opened 2024-09-26 09:58 UTC by Ariel0508

### 請說明這個 PR 的用途：

### 內容描述：
新增 首頁Yummy區塊，合併到 pages/Index

### 更改了什麼：
1. 新增 首頁 Yummy 區塊

### 是否有可能的問題：
1. 請協助檢查畫面是否有跑版

-----------------

提交 PR 前，請先檢查以下是否已完成：

* [ ] 查看 base branch
* [ ] 這支 PR 是否有明確的標題、內容描述

-----------------

2024-09-27 07:22 UTC, DolceTseng requested changes
字體再麻煩你微調一下，其他部份你辛苦了

2024-09-27 07:22 UTC, DolceTseng commented on pages/index.html
> +          <div class="fs-2 fw-bolder text-deco-pink text-nowrap">認領這邊請</div>
這裡應該是 40px (fs-1)

2024-09-27 07:22 UTC, DolceTseng commented on pages/index.html
> +          <h3 class="display-3 d-flex flex-column flex-lg-row justify-content-between">
電腦版是 display-1，手機版才會切到 display-3

2024-09-27 07:22 UTC, DolceTseng commented on pages/index.html
> +            <div class="deco-eyes position-relative">
辛苦你了這個瘋子圖示 🫠

2024-09-27 09:39 UTC, Ariel0508 commented on pages/index.html
> +            <div class="deco-eyes position-relative">
設計師畫的很開心我切得很痛苦 >~<

2024-09-27 10:01 UTC, DolceTseng commented on pages/index.html
> +            <div class="deco-eyes position-relative">
我…我感受到了😢

2024-09-27 10:16 UTC, Ariel0508 commented on pages/index.html
> +          <div class="fs-2 fw-bolder text-deco-pink text-nowrap">認領這邊請</div>
已更正，感謝 0V0

2024-09-27 10:16 UTC, Ariel0508 commented on pages/index.html
> +          <h3 class="display-3 d-flex flex-column flex-lg-row justify-content-between">
已更正，感謝 0V0

2024-09-28 03:49 UTC, DolceTseng commented on assets/scss/pages/_index.scss
> +    width: 55%;
這是什麼神奇的小東西？

2024-09-28 04:35 UTC, Ariel0508 commented on assets/scss/pages/_index.scss
> +    width: 55%;
因為字變大了，畫面大於1400px 時，原本是給  60% 的寬，改成給 55% ><
尼素要問介個嗎？

2024-09-28 04:41 UTC, DolceTseng commented on assets/scss/pages/_index.scss
> +    width: 55%;
不素，我素看到你用 @include ，才發現我完全忘記了可以設這個XD 不過我們用 Bootstrap 感覺使用這個的機會就少很多？
沒事，我只是閒聊

2024-09-29 04:32 UTC, Ariel0508 commented on assets/scss/pages/_index.scss
> +    width: 55%;
https://bootstrap5.hexschool.com/docs/5.0/layout/breakpoints/
用 Bootstrap 好像很常醬設？

2024-09-30 05:19 UTC, DolceTseng commented on assets/scss/pages/_index.scss
> +    width: 55%;
有，我後來看 bootstrap 文件看到了XD 笑死

2024-09-30 05:19 UTC, DolceTseng approved these changes

2024-10-01 08:05 UTC, chang88126 approved these changes

2024-10-01 08:05 UTC, jing607 approved these changes

2024-10-01 08:05 UTC, merged